name: Main Workflow Using Reusable Sum Workflow

on: [push]

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
  tree:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        shell: bash
        run: |
          tree -a
          
  invoke_reusable:
    runs-on: ubuntu-latest
    steps:
      - name: Invoke reusable workflow
        id: invoke_reusable
        uses: tony92151/my-reuse-github-action/.github/workflows/reuse-test.yaml@main
      - name: Set output
        id: set_output
        run: echo "::set-output name=computed_sum::${{ steps.invoke_reusable.outputs.sum }}"
    outputs:
      computed_sum: ${{ steps.set_output.outputs.computed_sum }}
      

  display_sum:
    needs: invoke_reusable
    runs-on: ubuntu-latest
    steps:
      - name: Display Sum
        run: echo "The sum is ${{ needs.invoke_reusable.outputs.computed_sum }}"
