name: Main Workflow Using Reusable Sum Workflow

on: [push]

jobs:
  invoke_reusable:
    uses: ./.github/workflows/reusable-sum-workflow.yml
    with:
      value_1: 10
      value_2: 20
    outputs:
      computed_sum: ${{ steps.invoke_reusable.outputs.sum }}

  display_sum:
    needs: invoke_reusable
    runs-on: ubuntu-latest
    steps:
      - name: Display Sum
        run: echo "The sum is ${{ needs.invoke_reusable.outputs.computed_sum }}"
