name: Main Workflow Using Reusable Sum Workflow

on: [push]

jobs:
  invoke_reusable:
    uses: tony92151/my-reuse-github-action/.github/workflows/reuse-test.yaml@main
    with:
      value_1: 10
      value_2: 20
  set_sum:
    needs: invoke_reusable
    runs-on: ubuntu-latest
    env:
      sum: ${{ needs.invoke_reusable.outputs.sum }}
    steps:
      - name: Set sum
        run: echo "sum=${sum}" >> $GITHUB_OUTPUT

  display_sum:
    needs: [invoke_reusable, set_sum]
    runs-on: ubuntu-latest
    env:
      sum: ${{ needs.invoke_reusable.outputs.sum }}
    steps:
      - name: Display Sum
        run: echo "The sum is $sum"